#!/usr/bin/env bash

directory="foo"
file="bar"

# Check if directory exists
if [ -d "$directory" ]
then
	echo "$directory exists!"
else
	echo "$directory doesn't exist"
fi

# Check if file exists
if [ -f "$file" ]
then
	echo "$file exists!"
else
	echo "$file doesn't exist"
fi

# Check if file is empty
if [ -s "$file" ]
then
	echo "$file contains data"
else
	echo "$file is empty"
fi
