#!/usr/bin/env bash

# Associative array (key = value)
declare -A associative_array=(
	[key5]="five"
	[key6]="six"
	[key7]="7"
	[key72]="72"
)

# Access value
echo "Assigning value \"seven\" to key7"
associative_array[key7]="seven"

# Remove value
echo "Revoving key[72]"
unset "associative_array[key72]"

# Add value by indexi
echo "Adding [key8]=\"eight\""
associative_array+=([key8]="eight")

# Associative arrays: Print keys
echo "Array keys:"
echo "${!associative_array[@]}"

# Length
# or ${associative_array[*]}"
echo "associative_array has ${#associative_array[@]} elements" 

# Iterating over array
echo "Array content:"
for k in "${!associative_array[@]}"
do
	echo -e " \tkey: $k, value: ${associative_array[${k}]}"
done

# Print all values
# or ${associative_array[*]}
echo "${associative_array[@]}"

# Check if element is present
if [[ -n "${associative_array[key8]}" ]] 
then
  echo "key8 exists"
else
  echo "key8 does not exists"
fi

# Remove array
unset associative_array

